% This script utilizes the metadata recorded at time of data aquisition to 
% calculate the time elapsed between embryo lysis and data acquisition

function elapsedTime = getElapsedTime(expDir, imgName)
%% Specify import options - autogenerated by matlab script generator using import on home tab
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "";

% Specify column names and types
opts.VariableNames = "Width0";
opts.VariableTypes = "categorical";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Width0", "EmptyFieldRule", "auto");

%% Import the metadata
metaData = readtable([expDir imgName '_MMStack_Default_metadata.txt'], opts);

%% Find aquisition start time
startTime = 0;
n = 1;
while startTime == 0
    str = string(metaData{n,1});
    startTime = contains(str,'StartTime');
    if startTime
        str = split(str);
        aquisitionTime = str(3,1);
        aquisitionTime = str2double(split(aquisitionTime,':'));
    end
    n = n+1;
end

%% Find lysis of time
finalShotTime = 0;
s = 4;
while finalShotTime == 0
    str = string(metaData{n,1});
    shotTime = contains(str,'Shot Times');
    while shotTime == 1
        if contains((string(metaData{n+3,1})),'}')
            elapsedTime = 'No Shot Times Recorded';
            return
        end
        str = string(metaData{n+s,1});
        finalShotTime = contains(str,']');
        if finalShotTime
            str = string(metaData{(n+s)-1,1});
            str = split(str);
            lysisTime = str(2,1);
            lysisTime = str2double(split(lysisTime,':'));
            shotTime = 0;
        end
        s = s+1;
    end
    n = n+1;
end
%% Calculate seconds elapsed between lysis and acquisition, if possible
aquisitionTime= (aquisitionTime(2)*60) + aquisitionTime(3);
lysisTime= (lysisTime(2)*60) + lysisTime(3);
elapsedTime = aquisitionTime - lysisTime;
end