% This script utilizes the metadata recorded at time of data aquisition to 
% calculate the time elapsed between embryo lysis and data acquisition

function elapsedTime = getElapsedTime(expDir, imgName, isNDTiff)

if isNDTiff
    %% Load the metadata
    dataset = javaObject('org.micromanager.ndtiffstorage.NDTiffStorage', expDir);
    smdJSON = dataset.getSummaryMetadata();
    smd = jsonObjectToStruct(smdJSON);
    %% Find acquisition start time
    acquisitionTime = split(smd.StartTime);
    acquisitionTime = str2double(split(acquisitionTime(2),':'));
    %% Find time of lysis
    if isempty(smd.UserData.Shot_Times.array)
        elapsedTime = 'No Shot Times Recorded';
        return
    else
        lysisTime = split(smd.UserData.Shot_Times.array(end));
        lysisTime = str2double(split(lysisTime(2),':'));
    end
else
    % This section assumes we have a micro-manager OME-TIFF with a separate
    % metadata file. This file needs to be read in as a table and decoded.
    %% Load the metadata
    % Specify import options - autogenerated by matlab script generator using import on home tab
    opts = delimitedTextImportOptions("NumVariables", 1);
    
    % Specify range and delimiter
    opts.DataLines = [1, Inf];
    opts.Delimiter = "";
    
    % Specify column names and types
    opts.VariableNames = "Width0";
    opts.VariableTypes = "categorical";
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    % Specify variable properties
    opts = setvaropts(opts, "Width0", "EmptyFieldRule", "auto");
    
    % Import the metadata
    metaData = readtable([expDir imgName '_MMStack_Pos0_metadata.txt'], opts);

    %% Find aquisition start time
    startTime = 0;
    n = 1;
    while startTime == 0
        str = string(metaData{n,1});
        startTime = contains(str,'StartTime');
        if startTime
            str = split(str);
            acquisitionTime = str(3,1);
            acquisitionTime = str2double(split(acquisitionTime,':'));
        end
        n = n+1;
    end
    
    %% Find time of lysis
    finalShotTime = 0;
    s = 4;
    while finalShotTime == 0
        str = string(metaData{n,1});
        shotTime = contains(str,'Shot Times');
        while shotTime == 1
            if contains((string(metaData{n+3,1})),'}') % If no shots were recorded, three lines after the string "Shot Times" in the metadata, there will be a right curly bracket. If metadata format is altered in the future, the algorithm will have to changed.
                elapsedTime = 'No Shot Times Recorded';
                return
            end
            str = string(metaData{n+s,1});  % If a single shot was fired, 4 lines after the string "Shot Times" in the metadata, there will be a right bracket. This is why "s" is set to 4 initially.
            finalShotTime = contains(str,']'); % However, if the laser was fired more than once, thre will be another time stamp rather than a right bracket. The loop iterates until it finds a right bracket- the line after the final shot. If metadata format is altered in the future, the algorithm will have to changed.
            if finalShotTime
                str = string(metaData{(n+s)-1,1});
                str = split(str);
                lysisTime = str(2,1);
                lysisTime = str2double(split(lysisTime,':'));
                shotTime = 0;
            end
            s = s+1;
        end
        n = n+1;
    end
end

%% Calculate seconds elapsed between lysis and acquisition, if possible
acquisitionTime= (acquisitionTime(2)*60) + acquisitionTime(3);
lysisTime= (lysisTime(2)*60) + lysisTime(3);
elapsedTime = acquisitionTime - lysisTime;
end